#!/usr/bin/env python3
"""Deterioration timeline generator. Case-agnostic.

    python3 engine/deterioration_timeline.py [cases/AFRVR]

Authoring section 14.2c requires this artifact for any case that uses a time-guarded
transition, and until now it was written by hand, which meant it could disagree with the
case file and nobody would know. The per-key review matrix cannot show any of this,
because it enumerates what a key resolves to IN a phase and knows nothing about how the
phase was reached, and the whole point of a time-guarded transition is that it is reached
by nobody doing anything.

Three sections, per 14.2c:

  1. every time-guarded exit, by phase, with its guard, its destination and the prompts
     that precede it, so each row can be read against two questions: would this patient
     really deteriorate in that time, and was the resident warned early enough to act.
  2. the do-nothing trajectory, which is the path an author is least likely to have
     imagined and the one a frozen learner actually sees.
  3. every narration line collected together, to be read against the vitals of the phase
     each one introduces. A narration saying the pressure has fallen, on a transition
     whose destination has the same systolic pressure, is a contradiction between the
     text and the monitor rather than an error in either, and no validator can see it.

Writes <PREFIX>-deterioration-timeline.md into the pack. A case with no time-guarded
transition writes nothing and says so.
"""
import json, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from validate_case import parse_condition, evaluate, atoms_of
from paths import resolve_pack

PACK = resolve_pack(sys.argv)
case = json.load(open(PACK.case))
PH = {p["id"]: p for p in case["phases"]}
ACT = {a["catalog_id"]: a for a in case["case_actions"]}
START = case["phases"][0]["id"]


def holds(cond, phase, flags=()):
    if not cond:
        return True
    assign = {("phase", p): (p == phase) for p in PH}
    for f in flags:
        assign[("flag", f)] = True
    return evaluate(parse_condition(cond)[0], assign)


def tag_in(action, phase, flags=()):
    for r in action["tag"]:
        if r.get("when") is None or holds(r["when"], phase, flags):
            return r["value"]
    return "neutral"


def prompts_in(phase, flags=()):
    out = []
    for a in case["case_actions"]:
        pr = a.get("prompt")
        if not pr or tag_in(a, phase, flags) != "critical":
            continue
        if pr.get("guard") and not holds(pr["guard"], phase, flags):
            continue
        out.append((pr["deadline_seconds"], a["catalog_id"], "first", pr["text"]))
        esc = pr.get("escalation")
        if esc:
            out.append((esc["deadline_seconds"], a["catalog_id"], "escalation", esc["text"]))
    return sorted(out)


def vit(pid):
    v = PH[pid]["vitals"]
    return (f"HR {v['heart_rate']}, BP {v['systolic_bp']}/{v['diastolic_bp']}, "
            f"RR {v['respiratory_rate']}, SpO2 {v['oxygen_saturation']}%, "
            f"T {v['temperature_c']}")


def timed_of(pid):
    return [(i, t) for i, t in enumerate(PH[pid].get("transitions", []))
            if "after_seconds" in t]


timed_any = any(timed_of(p) for p in PH)
out = []
W = out.append
prefix = PACK.prefix
W(f"# {prefix} deterioration timeline")
W("")
W("Generated by `engine/deterioration_timeline.py`. Authoring section 14.2c. Read it "
  "alongside the per-key review matrix, which cannot show any of this.")
W("")

if not timed_any:
    W("**This case authors no time-guarded transition.** Nothing changes unless the resident "
      "changes it, and section 14.2c does not apply.")
    open(PACK.path("deterioration-timeline.md"), "w").write("\n".join(out) + "\n")
    print("no time-guarded transitions; wrote a stub")
    sys.exit(0)

# ---------------------------------------------------------------- 1
W("## 1. Every time-guarded exit, by phase")
W("")
W("Two questions per row. Would this patient really deteriorate in that time if that "
  "treatment were withheld, and was the resident warned early enough to act on it.")
W("")
for pid in PH:
    tl = timed_of(pid)
    if not tl:
        continue
    W(f"### `{pid}`: {PH[pid]['label']}")
    W("")
    W(f"Vitals in this phase: {vit(pid)}")
    W("")
    for i, t in tl:
        dest = t["to"]
        mf = t.get("measured_from", "phase_entry")
        W(f"**Rule {i}: at {t['after_seconds']}s (measured from {mf}) → `{dest}`"
          + ("  (TERMINAL)" if PH[dest].get("terminal") else "") + "**")
        W("")
        W(f"- guard: `{t.get('when') or '(none: fires regardless)'}`")
        W(f"- destination vitals: {vit(dest)}")
        if t.get("allow_time_to_terminal"):
            W("- **opted in to ending the case on the clock**")
        W(f"- narration: “{t.get('narration','')}”")
        W(f"- author rationale: {t.get('author_rationale','MISSING')}")
        W("")
        # flags the guard requires unset
        need = set()
        w = t.get("when") or ""
        if "NOT" in w.upper():
            need = {a.ident for a in atoms_of(parse_condition(w)[0]) if a.kind == "flag"}
        ps = prompts_in(pid)
        if need:
            W(f"Prompts in this phase that set {', '.join(sorted(need))}, which is what the "
              f"fairness rule requires:")
            W("")
            hit = [p for p in ps if need & (set(ACT[p[1]].get("flags_set") or []))]
            if not hit:
                W("- **NONE. This is a trap rather than a lesson.**")
            for d, aid, kind, txt in hit:
                lead = t["after_seconds"] - d
                W(f"- `{aid}` {kind} at {d}s, {lead}s of lead"
                  + ("" if lead >= 20 else "  **UNDER THE 20s FLOOR**"))
            W("")
        cap = case.get("prompt_cap_recommendation", {}).get("per_phase", 3)
        W(f"All prompts schedulable in this phase, in firing order (per-phase cap is {cap}, "
          f"so only the first {cap} are heard):")
        W("")
        for n, (d, aid, kind, txt) in enumerate(ps):
            mark = "" if n < cap else "  **suppressed by the cap**"
            late = "  **AT OR AFTER THE EXIT**" if d >= t["after_seconds"] and mf == "phase_entry" else ""
            W(f"{n+1}. {d}s `{aid}` ({kind}){mark}{late}")
        W("")

# ---------------------------------------------------------------- 2
W("## 2. The do-nothing trajectory")
W("")
W("What a resident who performs no state-changing action at all sees, from arrival to "
  "wherever the case leaves them. This is the path an author is least likely to have "
  "imagined and the one a frozen learner will actually be looking at.")
W("")
t, pid, seen = 0, START, []
W("| clock | phase | vitals | how it was reached |")
W("|---|---|---|---|")
W(f"| 0:00 | `{pid}` | {vit(pid)} | arrival |")
for _ in range(20):
    if PH[pid].get("terminal"):
        break
    cands = [(tr["after_seconds"], i, tr) for i, tr in timed_of(pid)
             if (tr.get("measured_from", "phase_entry") == "phase_entry"
                 and holds(tr.get("when"), pid))]
    if not cands:
        break
    d, i, tr = min(cands)
    t += d
    pid = tr["to"]
    W(f"| {t//60}:{t%60:02d} | `{pid}` | {vit(pid)} | rule {i} fired at {d}s |")
    if pid in seen:
        W("| | | | **cycle** |")
        break
    seen.append(pid)
W("")
if PH[pid].get("terminal"):
    W("**The last row is a terminal phase.** This case can end without the resident touching "
      "the patient. That should be a decision the author remembers making.")
else:
    W(f"**The trajectory stops at `{pid}`, which is not terminal.** The clock cannot end this "
      f"case: a resident who does nothing at all reaches this phase and stays in it. Whether "
      f"that is the right teaching claim for this presentation is the author's call.")
W("")

# ---------------------------------------------------------------- 3
W("## 3. Every narration line, against the vitals it introduces")
W("")
W("A narration is the one place a nurse may describe a trajectory, because one has just "
  "happened and the monitor is about to show it. The constraint is the mirror image of the "
  "one on prompts: each line has to be true of the numbers displayed immediately afterwards. "
  "Read each row across.")
W("")
W("| from | at | to | vitals immediately after | the line |")
W("|---|---|---|---|---|")
for pid in PH:
    for i, tr in timed_of(pid):
        W(f"| `{pid}` | {tr['after_seconds']}s | `{tr['to']}` | {vit(tr['to'])} | "
          f"“{tr.get('narration','')}” |")
W("")
W("Compare each line with the row before it in section 2, not only with the destination: a "
  "line saying a number has fallen must be preceded by a phase in which it was higher.")
W("")
W("**The vitals in every table above are the phase's AUTHORED numbers.** A vital effect running "
  "at the moment a transition fires will move what the monitor actually shows, and nothing in "
  "this file knows about that, because effects depend on when a drug was given and this file "
  "enumerates phases. Where a case guards an effect on a phase, read that effect's delta into "
  "the destination row by hand before judging the narration against it.")

open(PACK.path("deterioration-timeline.md"), "w").write("\n".join(out) + "\n")
print(f"wrote {prefix}-deterioration-timeline.md")
