#!/usr/bin/env python3
"""Path resolution shared by every engine tool.

Layout:

    <root>/
      engine/     case-agnostic code and tools. Contains no clinical content.
      catalog/    global action and diagnosis catalogs, and their generators.
      cases/      one folder per case, each holding a case pack.
      docs/       specification.
      build/      generated prototypes.

A **case pack** is a folder whose files share a prefix. For the reference case the
prefix is CHFE and the folder is `cases/CHFE/`:

    CHFE-case.json          the case file
    CHFE-binding-map.json   authored case-id to catalog-id map
    CHFE-scenarios.json     end-to-end paths the simulator walks
    CHFE-tests.js           case-specific engine assertions
    CHFE-binding.json       generated by bind_catalog.py
    CHFE-review-matrix.md   generated by validate_case.py

Every pack in `cases/` is packed into a single `build/simulator.html`, which opens on
a case picker. Cases share one copy of the catalog, so a second case costs only the
size of its own case file.

Every tool takes a case pack as its argument, either as a folder (`cases/CHFE`) or
as a prefix (`CHFE`). Nothing in engine/ hard-codes a case name.
"""
import os, sys, glob

ENGINE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(ENGINE)
CATALOG_DIR = os.path.join(ROOT, "catalog")
CASES_DIR = os.path.join(ROOT, "cases")
BUILD_DIR = os.path.join(ROOT, "build")
DOCS_DIR = os.path.join(ROOT, "docs")


class CasePack:
    """One case's folder, addressed by prefix."""

    def __init__(self, ref):
        ref = ref.rstrip("/")
        if os.path.isdir(ref):
            self.dir = os.path.abspath(ref)
        elif os.path.isdir(os.path.join(CASES_DIR, ref)):
            self.dir = os.path.join(CASES_DIR, ref)
        elif os.path.isfile(ref):
            self.dir = os.path.dirname(os.path.abspath(ref))
        else:
            raise SystemExit(f"no case pack found for {ref!r}; looked in {CASES_DIR}")
        self.prefix = self._infer_prefix()

    def _infer_prefix(self):
        hits = glob.glob(os.path.join(self.dir, "*-case.json"))
        if not hits:
            raise SystemExit(f"{self.dir} contains no *-case.json")
        if len(hits) > 1:
            raise SystemExit(f"{self.dir} contains more than one *-case.json: {hits}")
        return os.path.basename(hits[0])[: -len("-case.json")]

    def path(self, suffix):
        return os.path.join(self.dir, f"{self.prefix}-{suffix}")

    # canonical members
    @property
    def case(self):        return self.path("case.json")
    @property
    def binding_map(self): return self.path("binding-map.json")
    @property
    def binding(self):     return self.path("binding.json")
    @property
    def scenarios(self):   return self.path("scenarios.json")
    @property
    def tests(self):       return self.path("tests.js")
    @property
    def matrix(self):      return self.path("review-matrix.md")
    # There is one simulator for all packs; see engine/build_simulator.py.
    @property
    def simulator(self):   return os.path.join(BUILD_DIR, "simulator.html")

    def __repr__(self):
        return f"<CasePack {self.prefix} at {self.dir}>"


def catalog_path(name):
    return os.path.join(CATALOG_DIR, name)


def resolve_pack(argv, index=1):
    """Take a case pack from argv, or the only one in cases/ if there is exactly one."""
    if len(argv) > index:
        return CasePack(argv[index])
    packs = [d for d in sorted(os.listdir(CASES_DIR))
             if os.path.isdir(os.path.join(CASES_DIR, d))
             and glob.glob(os.path.join(CASES_DIR, d, "*-case.json"))]
    if len(packs) == 1:
        return CasePack(packs[0])
    raise SystemExit(
        f"specify a case pack. Available: {', '.join(packs) if packs else '(none)'}")


def list_packs():
    return [d for d in sorted(os.listdir(CASES_DIR))
            if os.path.isdir(os.path.join(CASES_DIR, d))
            and glob.glob(os.path.join(CASES_DIR, d, "*-case.json"))]


if __name__ == "__main__":
    print("root:   ", ROOT)
    print("catalog:", CATALOG_DIR)
    print("cases:  ", CASES_DIR)
    for p in list_packs():
        pk = CasePack(p)
        print(f"  {pk.prefix:<8} {pk.dir}")
