#!/usr/bin/env python3
"""One-shot: give each case a content_keys.patient_visual. No case authors a patient.avatar:
every case draws the standard man or woman (SHARED.patient.base) by patient.sex.
CHFE and MGCA are authored JSON and are edited as JSON. AFRVR and DIPH are generated by
their build_case.py, so their Python sources are edited and the JSON is regenerated."""
import json, os, subprocess, sys
ROOT = sys.argv[1]

NOTE = ("MODEL-AUTHORED, NOT PHYSICIAN-AUTHORED. Drives the figure in the room (engine/patient.js). "
        "Derived from this case's own phase descriptions, alertness levels and general status lines, "
        "and adds no clinical fact of its own: eyes closed where the phase is unresponsive, sedated or "
        "arrested; work of breathing where the phase description names it. The respiratory rate is "
        "not authored here, the figure breathes at the monitor's rate. Verify each rule against the "
        "phase it names, as for any other content key.")

CASES = {
 "CHFE": {
  "rules": [
   {"when": "phase is post_intubation_hypotension OR phase is intubated_stabilized OR phase is halted",
    "value": {"eyes": "closed"}},
   {"when": "phase is impending_respiratory_failure",
    "value": {"eyes": "open", "work_of_breathing": "severe"}},
   {"when": "phase is presentation",
    "value": {"eyes": "open", "work_of_breathing": "severe", "addons": ["nasal_cannula"]}},
   {"when": "phase is niv_supported OR phase is nitrate_responding",
    "value": {"eyes": "open", "work_of_breathing": "increased"}},
   {"when": None, "value": {"eyes": "open", "work_of_breathing": "normal"}}],
  "verify": ("The nasal cannula is drawn only in the arrival phase, from the EMS handover (6 L/min en "
             "route). It does not yet follow the oxygen and NIV actions; when mask and tube artwork "
             "exist these rules should be rewritten on flags rather than phases."),
 },
 "MGCA": {
  "rules": [
   {"when": "phase is cardiac_arrest OR phase is halted OR phase is frank_septic_shock",
    "value": {"eyes": "closed"}},
   {"when": None, "value": {"eyes": "open", "work_of_breathing": "normal"}}],
  "verify": ("frank_septic_shock is drawn with eyes closed because its description places it after "
             "induction and positive pressure ventilation. Tachypnoea in this case is drawn as rate "
             "only, with no increased effort, because no phase description names respiratory effort."),
 },
 "AFRVR": {
  "rules": [
   {"when": "phase is intubated OR phase is halted", "value": {"eyes": "closed"}},
   {"when": "phase is respiratory_failure OR phase is rate_controlled_congested",
    "value": {"eyes": "open", "work_of_breathing": "severe"}},
   {"when": "phase is presentation", "value": {"eyes": "open", "work_of_breathing": "increased"}},
   {"when": None, "value": {"eyes": "open", "work_of_breathing": "normal"}}],
  "verify": ("presentation is drawn as increased rather than severe because he can still finish a "
             "sentence; rate_controlled_congested is drawn as severe from 'still working hard to "
             "breathe' at distress level 3. respiratory_failure is drowsy and is drawn eyes open."),
 },
 "DIPH": {
  "rules": [
   {"when": "flag airway_protected set OR phase is pulseless_vt OR phase is halted",
    "value": {"eyes": "closed"}},
   {"when": "phase is seizing", "value": {"eyes": "open", "seizure": True}},
   {"when": "phase is post_ictal", "value": {"eyes": "closed"}},
   {"when": None, "value": {"eyes": "open", "work_of_breathing": "normal"}}],
  "verify": ("Three choices to check. (1) The convulsion is drawn with the eyes OPEN, on the "
             "understanding that the eyes are usually open in a generalised tonic-clonic seizure "
             "and that closed eyes during the event point toward a functional seizure; change it "
             "if that is not what should be taught. (2) Once airway_protected is set the figure is "
             "still and eyes closed even in the seizing phase, on the assumption of induction and "
             "paralysis; a paralysed patient may still be seizing electrically and the figure "
             "cannot show that. (3) post_ictal is drawn eyes closed from 'drowsy', at alertness "
             "level 1."),
 },
}

def block(c):
    return {"authoring_note": NOTE, "verify": c["verify"], "rules": c["rules"]}

# ---- authored JSON
for pre in ("CHFE", "MGCA"):
    p = os.path.join(ROOT, "cases", pre, pre + "-case.json")
    j = json.load(open(p))
    ck = j["content_keys"]; new = {}
    for k, v in ck.items():                      # keep order; sit right after general_status
        new[k] = v
        if k == "general_status": new["patient_visual"] = block(CASES[pre])
    assert "patient_visual" in new
    j["content_keys"] = new
    with open(p, "w") as f:
        json.dump(j, f, indent=1, ensure_ascii=False); f.write("\n")
    print("edited", p)

# ---- generated JSON: edit the Python, then regenerate
def pylit(o, ind=1):
    """json with Python booleans and None, indented like the surrounding source."""
    s = json.dumps(o, indent=1, ensure_ascii=False)
    return s.replace(": true", ": True").replace(": false", ": False").replace(": null", ": None")

for pre in ("AFRVR", "DIPH"):
    d = os.path.join(ROOT, "cases", pre)
    content = os.path.join(d, "case_3_content.py"); s = open(content).read()
    assert "PATIENT_VISUAL" not in s and s.count("\nLABS = {") == 1
    s = s.replace("\nLABS = {",
        "\n# What the figure in the room is doing (engine/patient.js). A guarded rule list like\n"
        "# GENERAL_STATUS above, and kept consistent with it: both describe the same patient.\n"
        "PATIENT_VISUAL = " + pylit(block(CASES[pre])) + "\n\nLABS = {")
    open(content, "w").write(s)
    b = os.path.join(d, "build_case.py"); s = open(b).read()
    a1 = "from case_3_content import EXAM, GENERAL_STATUS, LABS, IMAGING, CONSULTANTS"
    a2 = '   "general_status": GENERAL_STATUS,\n'
    assert s.count(a1) == 1 and s.count(a2) == 1
    s = s.replace(a1, "from case_3_content import EXAM, GENERAL_STATUS, PATIENT_VISUAL, LABS, IMAGING, CONSULTANTS")
    s = s.replace(a2, a2 + '   "patient_visual": PATIENT_VISUAL,\n')
    open(b, "w").write(s)
    subprocess.check_call([sys.executable, b, d])
print("done")
